force-app/main/default/objects/Account/recordTypes/Abacus.recordType-meta.xml
<RecordType>
    <fullName>Abacus</fullName>
    <active>true</active>
    <label>Abacus B2C Person Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/SFCC_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>SFCC_Order_Number__c</fullName>
    <description>This field holds Salesforce Commerce Cloud Order Number.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field holds Salesforce Commerce Cloud Order Number.</inlineHelpText>
    <label>Website Order Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Store_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Store_Purchase__c</fullName>
    <label>Store Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B001_Balmes</fullName>
            </value>
            <value>
                <fullName>B002_Sabadell</fullName>
            </value>
            <value>
                <fullName>B003_Sta_Coloma</fullName>
            </value>
            <value>
                <fullName>B004_Urquinaona</fullName>
            </value>
            <value>
                <fullName>B006_Badalona</fullName>
            </value>
            <value>
                <fullName>B007_RS_SSCC</fullName>
            </value>
            <value>
                <fullName>B008_BAIXA</fullName>
            </value>
            <value>
                <fullName>B010_Sants</fullName>
            </value>
            <value>
                <fullName>B011_Bellaterra_(UAB)</fullName>
            </value>
            <value>
                <fullName>B016_Girona</fullName>
            </value>
            <value>
                <fullName>B017_València_Centre</fullName>
            </value>
            <value>
                <fullName>B018_Baixa</fullName>
            </value>
            <value>
                <fullName>B019_Perú</fullName>
            </value>
            <value>
                <fullName>B020_Pompeu_(UPF)</fullName>
            </value>
            <value>
                <fullName>B021_Lleida</fullName>
            </value>
            <value>
                <fullName>B022_Vic_Universitària</fullName>
            </value>
            <value>
                <fullName>B023_Tarragona</fullName>
            </value>
            <value>
                <fullName>B024_Sant_Andreu</fullName>
            </value>
            <value>
                <fullName>B025_Manresa</fullName>
            </value>
            <value>
                <fullName>B026_Reus</fullName>
            </value>
            <value>
                <fullName>B027_Mataró</fullName>
            </value>
            <value>
                <fullName>B028_Sant_Boi</fullName>
            </value>
            <value>
                <fullName>B029_Vilanova_i_la_Geltrú</fullName>
            </value>
            <value>
                <fullName>B032_Mollet</fullName>
            </value>
            <value>
                <fullName>B033_Igualada</fullName>
            </value>
            <value>
                <fullName>B034_Granollers</fullName>
            </value>
            <value>
                <fullName>B035_Vic</fullName>
            </value>
            <value>
                <fullName>B036_Figueres</fullName>
            </value>
            <value>
                <fullName>B039_L_ILLA</fullName>
            </value>
            <value>
                <fullName>B043_Sant_Cugat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Renglo__c.field-meta.xml
<CustomField>
    <fullName>Renglo__c</fullName>
    <label>Rengló</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OSF_OrderTriggerHandlerTest.cls
@isTest
public class OSF_OrderTriggerHandlerTest {
    @isTest static void createOrderRecordsWithAccount() {
        Id id1 = [select id, name from profile where name = 'SCC Integration User'].id;
        user u = new user (lastName = 'Test RollUps',profileId = id1,Alias = 'uscci',
                           Email = 'abacus-pj+test@osf.digital',
                           UserName = 'abacus-pj+test@osf.digital',
                           EmailEncodingKey = 'UTF-8',LanguageLocaleKey = 'en_US',LocaleSidKey = 'en_US',TimeZoneSidKey = 'America/Chicago');
        system.RunAs(u) {
            Pricebook2 standardPricebook = new Pricebook2(
                Id = Test.getStandardPricebookId(),
                pricebook_external_id__c = 'Standard Price Book',
                IsActive = true
            );
            
            Update standardPricebook;
            //Insert Product
            list<Product2> prList = new list<Product2>();
            prList.add(new Product2(Name = 'CLE Littérature Progressive AVA 2E/Cor Cle 9782090351828', ProductCode = '1326798.78', Description = 'Fa anys, a la vall de Gudbrandsdalen van néixer unesbessones que, del maluc cap avall, eren una. De grans, van treballar de tapisseres i, de les seves obres,es deia que predeien el futur. Quan van morir, el seupare va fer fondre dues campanes en memòria seva que, pel seu repic poderós, van convertir Butangen en unpunt de referència, fins l’any 1880. Aleshores, elsnous temps van arribar al poble i tres destins es vancreuar: el d’un jove pastor, el d’un il·lustrador destavkirke alemany i el de l’Astrid, una minyona de la granja Hekne, on les bessones havien nascut seglesenrere. Aquest és el primer llibre d’una trilogia.', Renglo__c = '05 FICCIO', Source_Absis__c = True));
            insert prList;
            //Insert Pricebook
            list<Pricebook2> pbList = new list<Pricebook2>();
            pbList.add(new Pricebook2(Name = 'Diferit', pricebook_external_id__c = 'Diferit'));
            insert pbList;
            //Insert pricebook entry
            list<PricebookEntry> pbeList = new list<PricebookEntry>();
            pbeList.add(new PricebookEntry(Pricebook2Id = pbList[0].Id, Product2Id = prList[0].Id, UnitPrice = 7.05, IsActive = true));
            insert pbeList;  
            //
            Test.startTest();
            RecordType recordType = SCCUtilityClass.getPersonAccountRecordType('Person Account');
            Account act = new Account(firstName = 'Steve', lastName = 'Smith', recordTypeId = recordType.Id, SAP_ID__c = '73218390');
            insert act;
            list<Order> ordList = new list<Order>();
            list<OrderItem> ordItemList = new list<OrderItem>();
            ordList.add(new order (Pricebook2Id = pbList[0].Id, effectiveDate = system.today()-265 , Store_Purchase__c = 'B001_Balmes', Status = 'Entregat_client', SFCC_Order_Total__c = 18.19, Order_SCCSync_Status__c = 'Synchronised', SFCC_Order_Number__c = '00000101', accountId = act.Id));
            ordList.add(new order (Pricebook2Id = pbList[0].Id, effectiveDate = system.today()-263 , Store_Purchase__c = 'B018_Baixa', Status = 'Entregat_client', SFCC_Order_Total__c = 12.19, Order_SCCSync_Status__c = 'Synchronised', SFCC_Order_Number__c = '00000102', accountId = act.Id));
            insert ordList;
            ordList[0].SFCC_Order_Total__c += ordList[0].SFCC_Order_Total__c;
            update ordList;
            
            ordItemList.add(new OrderItem(orderId = ordList[0].Id, PricebookEntryId = pbeList[0].Id, UnitPrice = 7.05, Quantity = 2));
            insert ordItemList;
            delete ordItemList;
            delete ordList[0];
            Test.stopTest();
        }
        
    }
}