force-app/main/default/objects/Account/fields/Last_purchase_date__c.field-meta.xml
<CustomField>
    <fullName>Last_purchase_date__c</fullName>
    <label>Last purchase date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nr_of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Nr_of_Orders__c</fullName>
    <label>Nr of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nr_of_Orders_this_year__c.field-meta.xml
<CustomField>
    <fullName>Nr_of_Orders_this_year__c</fullName>
    <label>Nr of Orders this year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Amount_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Orders__c</fullName>
    <label>Total Amount Orders</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_sum_of_Orders_this_year__c.field-meta.xml
<CustomField>
    <fullName>Total_sum_of_Orders_this_year__c</fullName>
    <label>Total sum of Orders this year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Abacus.recordType-meta.xml
<RecordType>
    <fullName>Abacus</fullName>
    <active>true</active>
    <label>Abacus B2C Person Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/isOrderthisyear__c.field-meta.xml
<CustomField>
    <fullName>isOrderthisyear__c</fullName>
    <formula>IF( EffectiveDate &gt;=(TODAY()-365), 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isOrderthisyear</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OSF_RollUpAndPurchaseDateUptAccCntrl.cls
/**
* File:        OSF_OrderRollUpsOnAccountController.cls
* Project:     Abacus
* Date:        March 30, 2021
* Created By:  Fahad Farrukh
* *************************************************************************
* Description:  Order Rollups on Account
* *************************************************************************
* History:
* Date:                Modified By:             Description:
*/
public class OSF_RollUpAndPurchaseDateUptAccCntrl {
    /**
* @author Fahad Farrukh
* @date  March 31, 2021
* @name doRollUpsOnAccount
* @description RollUp Completed orders totals amount and count on their respective Accounts
* @return void
*/
    public static void doRollUpsOnAccount(Boolean IsUpdate,Boolean IsDelete,Map<id,Order> OrdListNewMap,Map<id,Order> OrdListOldMap) {
        Set<id> accountIds = new Set<id>();
        List<Account> accList;
        if (IsUpdate) {
            for (Id id1 : OrdListNewMap.keySet()) {
                if(!String.isBlank(OrdListNewMap.get(id1).AccountId))
                    accountIds.add(OrdListNewMap.get(id1).AccountId);
            }
        } else if (IsDelete) {
            for (Id id1: OrdListOldMap.keySet()) {
                if (!String.isBlank(OrdListOldMap.get(id1).AccountId))
                    accountIds.add(OrdListOldMap.get(id1).AccountId);
            }
        }
        accList = [SELECT id, Nr_of_Orders__c, Total_Amount_Orders__c,(SELECT id, TotalAmount, isOrderthisyear__c  FROM Orders WHERE status != 'Draft') FROM Account WHERE id IN : accountIds];
        Integer countOrdersOnAccount, countThisYearOrdersOnAccount;
        Decimal countTotalAmountOfOrdersOnAccount, countThisYearTotalAmountOfOrdersOnAccount;
        for (Account a : accList) {
            countOrdersOnAccount = 0;
            countTotalAmountOfOrdersOnAccount = 0;
            countThisYearOrdersOnAccount = 0;
            countThisYearTotalAmountOfOrdersOnAccount = 0;
            for (Order o : a.orders) {
                if (o.isOrderthisyear__c == 1) {
                    countThisYearOrdersOnAccount += 1;
                    if(o.TotalAmount!=null)
                    countThisYearTotalAmountOfOrdersOnAccount += o.TotalAmount;
                }
                if(o.TotalAmount!=null)
                countTotalAmountOfOrdersOnAccount += o.TotalAmount;
                countOrdersOnAccount+=1;   
            }
            a.Nr_of_Orders__c = countOrdersOnAccount;
            a.Total_Amount_Orders__c = countTotalAmountOfOrdersOnAccount;
            a.Nr_of_Orders_this_year__c = countThisYearOrdersOnAccount;
            a.Total_sum_of_Orders_this_year__c = countThisYearTotalAmountOfOrdersOnAccount;
        }
        if (accList.size() > 0)
            database.update(accList, false);  
    }
    /**
* @author Fahad Farrukh
* @date  March 31, 2021
* @name updateLastPurchaseDateOnAccount
* @description Update Last Purchase Date on Account
* @return void
*/   
    public static void updateLastPurchaseDateOnAccount(Boolean IsUpdate, Boolean IsDelete, Map<id,Order> OrdListNewMap, Map<id,Order> OrdListOldMap) {
        Set<id> accountIds = new Set<id>();
        List<Account> accList;
        if (IsUpdate) {
            for (Id id1 : OrdListNewMap.keySet()) {
                if (!String.isBlank(OrdListNewMap.get(id1).AccountId))
                    accountIds.add(OrdListNewMap.get(id1).AccountId);
            }
        } else if (IsDelete) {
            for (Id id1: OrdListOldMap.keySet()) {
                if (!String.isBlank(OrdListOldMap.get(id1).AccountId))
                    accountIds.add(OrdListOldMap.get(id1).AccountId);
            }
        }
        accList = [SELECT id, Last_purchase_date__c, (SELECT id, EffectiveDate FROM Orders) FROM Account WHERE id IN : accountIds];
        for (Account a : accList) {
            a.Last_purchase_date__c=NULL;
            for (Order o : a.orders) {
                if (a.Last_purchase_date__c == NULL) {
                    a.Last_purchase_date__c = o.EffectiveDate;
                } else if (a.Last_purchase_date__c < o.EffectiveDate) {
                    a.Last_purchase_date__c = o.EffectiveDate;
                }
            }
        }
        if (accList.size() > 0)
            database.update(accList, false);
    }
}