force-app/main/default/objects/Account/fields/Last_purchase_date__c.field-meta.xml
<CustomField>
    <fullName>Last_purchase_date__c</fullName>
    <label>Last purchase date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nr_of_Orders__c.field-meta.xml
<CustomField>
    <fullName>Nr_of_Orders__c</fullName>
    <label>Nr of Orders</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nr_of_Orders_this_year__c.field-meta.xml
<CustomField>
    <fullName>Nr_of_Orders_this_year__c</fullName>
    <label>Nr of Orders this year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Amount_Orders__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Orders__c</fullName>
    <label>Total Amount Orders</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_sum_of_Orders_this_year__c.field-meta.xml
<CustomField>
    <fullName>Total_sum_of_Orders_this_year__c</fullName>
    <label>Total sum of Orders this year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Abacus.recordType-meta.xml
<RecordType>
    <fullName>Abacus</fullName>
    <active>true</active>
    <label>Abacus B2C Person Account</label>
</RecordType>

force-app/main/default/objects/Order/fields/In_Store_Order__c.field-meta.xml
<CustomField>
    <fullName>In_Store_Order__c</fullName>
    <label>In Store Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Botiga física</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/isOrderthisyear__c.field-meta.xml
<CustomField>
    <fullName>isOrderthisyear__c</fullName>
    <formula>IF( EffectiveDate &gt;=(TODAY()-365), 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isOrderthisyear</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Store_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Store_Delivery__c</fullName>
    <label>Store Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B001_Balmes</fullName>
            </value>
            <value>
                <fullName>B002_Sabadell</fullName>
            </value>
            <value>
                <fullName>B003_Sta_Coloma</fullName>
            </value>
            <value>
                <fullName>B004_Urquinaona</fullName>
            </value>
            <value>
                <fullName>B006_Badalona</fullName>
            </value>
            <value>
                <fullName>B007_RS_SSCC</fullName>
            </value>
            <value>
                <fullName>B008_BAIXA</fullName>
            </value>
            <value>
                <fullName>B010_Sants</fullName>
            </value>
            <value>
                <fullName>B011_Bellaterra_(UAB)</fullName>
            </value>
            <value>
                <fullName>B016_Girona</fullName>
            </value>
            <value>
                <fullName>B017_València_Centre</fullName>
            </value>
            <value>
                <fullName>B018_Baixa</fullName>
            </value>
            <value>
                <fullName>B019_Perú</fullName>
            </value>
            <value>
                <fullName>B020_Pompeu_(UPF)</fullName>
            </value>
            <value>
                <fullName>B021_Lleida</fullName>
            </value>
            <value>
                <fullName>B022_Vic_Universitària</fullName>
            </value>
            <value>
                <fullName>B023_Tarragona</fullName>
            </value>
            <value>
                <fullName>B024_Sant_Andreu</fullName>
            </value>
            <value>
                <fullName>B025_Manresa</fullName>
            </value>
            <value>
                <fullName>B026_Reus</fullName>
            </value>
            <value>
                <fullName>B027_Mataró</fullName>
            </value>
            <value>
                <fullName>B028_Sant_Boi</fullName>
            </value>
            <value>
                <fullName>B029_Vilanova_i_la_Geltrú</fullName>
            </value>
            <value>
                <fullName>B032_Mollet</fullName>
            </value>
            <value>
                <fullName>B033_Igualada</fullName>
            </value>
            <value>
                <fullName>B034_Granollers</fullName>
            </value>
            <value>
                <fullName>B035_Vic</fullName>
            </value>
            <value>
                <fullName>B036_Figueres</fullName>
            </value>
            <value>
                <fullName>B039_L_ILLA</fullName>
            </value>
            <value>
                <fullName>B043_Sant_Cugat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Store_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Store_Purchase__c</fullName>
    <label>Store Purchase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B001_Balmes</fullName>
            </value>
            <value>
                <fullName>B002_Sabadell</fullName>
            </value>
            <value>
                <fullName>B003_Sta_Coloma</fullName>
            </value>
            <value>
                <fullName>B004_Urquinaona</fullName>
            </value>
            <value>
                <fullName>B006_Badalona</fullName>
            </value>
            <value>
                <fullName>B007_RS_SSCC</fullName>
            </value>
            <value>
                <fullName>B008_BAIXA</fullName>
            </value>
            <value>
                <fullName>B010_Sants</fullName>
            </value>
            <value>
                <fullName>B011_Bellaterra_(UAB)</fullName>
            </value>
            <value>
                <fullName>B016_Girona</fullName>
            </value>
            <value>
                <fullName>B017_València_Centre</fullName>
            </value>
            <value>
                <fullName>B018_Baixa</fullName>
            </value>
            <value>
                <fullName>B019_Perú</fullName>
            </value>
            <value>
                <fullName>B020_Pompeu_(UPF)</fullName>
            </value>
            <value>
                <fullName>B021_Lleida</fullName>
            </value>
            <value>
                <fullName>B022_Vic_Universitària</fullName>
            </value>
            <value>
                <fullName>B023_Tarragona</fullName>
            </value>
            <value>
                <fullName>B024_Sant_Andreu</fullName>
            </value>
            <value>
                <fullName>B025_Manresa</fullName>
            </value>
            <value>
                <fullName>B026_Reus</fullName>
            </value>
            <value>
                <fullName>B027_Mataró</fullName>
            </value>
            <value>
                <fullName>B028_Sant_Boi</fullName>
            </value>
            <value>
                <fullName>B029_Vilanova_i_la_Geltrú</fullName>
            </value>
            <value>
                <fullName>B032_Mollet</fullName>
            </value>
            <value>
                <fullName>B033_Igualada</fullName>
            </value>
            <value>
                <fullName>B034_Granollers</fullName>
            </value>
            <value>
                <fullName>B035_Vic</fullName>
            </value>
            <value>
                <fullName>B036_Figueres</fullName>
            </value>
            <value>
                <fullName>B039_L_ILLA</fullName>
            </value>
            <value>
                <fullName>B043_Sant_Cugat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OSF_KPICalculate_Batch.cls
/**
* File:        OSF_KPICalculate_Batch.cls
* Project:     Abacus
* Date:        July 22, 2021
* Created By:  Ali Ozdemir
* *************************************************************************
* Description:  Order Rollups on Account when an order is created, updated or deleted, Update last purchase date on Account, Update StorePurchase on Account
* *************************************************************************
* History:
* Date:                Modified By:             Description:
*/
public with sharing class OSF_KPICalculate_Batch implements Database.Batchable<sObject>, Database.Stateful {
    // for custom cache mechanism
    public Set<Id> accIds = new Set<Id>();

    /**
    * @author Ali Ozdemir
    * @date  July 22, 2021
    * @name start
    * @description get query locator
    * @return Database.QueryLocator
    */  
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, AccountId, isOrderthisyear__c, TotalAmount, EffectiveDate, Store_Purchase__c, 
                                            Store_Delivery__c, Interest_As_Purchase__c, In_Store_Order__c, Status FROM Order]);
    }
    
    /**
    * @author Ali Ozdemir
    * @date  July 22, 2021
    * @name execute
    * @description process data to prepare batches and prepare control set for accounts
    * @return void
    */ 
    public void execute(Database.BatchableContext BC, List<Order> ordList){
        Set<Id> accountIds = new Set<Id>();
        Map<String, List<Order>> ordersMap = new Map<String, List<Order>>();
        for(Order o : ordList) {
            accountIds.add(o.AccountId);
            if(ordersMap.containsKey(o.AccountId)) {
                List<Order> tempList = new List<Order>();
                tempList = ordersMap.get(o.AccountId);
                tempList.add(o);
                ordersMap.put(o.AccountId, tempList);
            } else {
                List<Order> tempList = new List<Order>();
                tempList.add(o);
                ordersMap.put(o.AccountId, tempList);
            }
        }
        List<Account> accList = [SELECT Id, Nr_of_Orders__c, Total_Amount_Orders__c, Nr_of_Orders_this_year__c, Reference_Store_Cache__c, Interest_As_Purchase_Cache__c,
                                Store_Delivery_Cache__c, Total_sum_of_Orders_this_year__c, Last_purchase_date__c FROM Account WHERE Id IN :accountIds];
        if(!accList.isEmpty()) {
            OSF_OrderTriggerHandler.doRollUpsOnAccount(accList, ordersMap, accIds);
            accIds.addAll(accountIds);
        }
    }
    
    /**
    * @author Ali Ozdemir
    * @date  July 22, 2021
    * @name finish
    * @description 
    * @return void
    */ 
    public void finish(Database.BatchableContext BC) {
    }
}