force-app/main/default/objects/Account/fields/osf_validPaymentTypes__c.field-meta.xml
<CustomField>
    <fullName>osf_validPaymentTypes__c</fullName>
    <label>Valid Payment Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>No Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Abacus.recordType-meta.xml
<RecordType>
    <fullName>Abacus</fullName>
    <active>true</active>
    <label>Abacus B2C Person Account</label>
</RecordType>

force-app/main/default/objects/osf_province_list__c/osf_province_list__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Province List provided by customer</description>
    <label>Province List</label>
</CustomObject>

force-app/main/default/classes/osf_ServiceAccount.cls
/**
 * File:        osf_ServiceAccount.cls
 * Project:     Abacus B2B (SP-ABCS-IFB-Abacus B2B Implementation (CCRZ))
 * Date:        Feb 1, 2020
 * Created By:  Cansu Asli Asci
  ************************************************************************
 * Description: Extension for Service Provider of Account Object
  ************************************************************************
 * History:
 */
global with sharing class osf_ServiceAccount extends ccrz.ccServiceAccount{
    
    @TestVisible private static final List<String> FIELD_LIST = new List<String> {'osf_validPaymentTypes__c'};
    

    /**********************************************************************************************
    * @Name         : getFieldsMap
    * @Description  : adds custom fields
    * @Created By   : Cansu Asli Asci
    * @param        : Map<String, Object>, inputData
    * @Return       : Map<String, Object>, outputData
    *********************************************************************************************/
    global override Map<String, Object> getFieldsMap (Map<String, Object> inputData) {
        Map<String, Object> outputData = super.getFieldsMap(inputData);
        String fields = (String) outputData.get(ccrz.ccService.OBJECTFIELDS);
        fields += osf_constant_strings.COMMA + String.join(FIELD_LIST, osf_constant_strings.COMMA);
        outputData.put(ccrz.ccService.OBJECTFIELDS, fields);
        return outputData;
    }

    /**********************************************************************************************
    * @Name         : prepReturn
    * @Description  : Modifying returned JSON model of Account Service.
    * @Created By   : Cansu Asli Asci
    * @param        : Map<String, Object>, inputData
    * @Return       : Map<String, Object>, outputData
    *********************************************************************************************/
    global override Map<String, Object> prepReturn(Map<String, Object> inputData) {
        Map<String,Object> outputData = super.prepReturn(inputData);
        try {
            if(ccrz.cc_CallContext.currPageName.contains(osf_constant_strings.MY_ACCOUNT_PAGE)){
                Map<String,osf_province_list__c> provinceMap = osf_province_list__c.getall();
                Set<String> provinceNameSet = provinceMap.keySet();
                List<String> provinceNames = new List<String>(provinceNameSet);
                provinceNames.sort();
                
                List<Object> accountList = (List<Object>) outputData.get(ccrz.ccApiAccount.ACCOUNTS);
                for(Object acc : accountList) {
                    Map<String, Object> account = (Map<String, Object>)acc;
                    account.put(osf_constant_strings.ACCOUNT_PROVINCE_LIST, provinceNames);
                }
            }
                
        } catch (Exception e) {
            ccrz.ccLog.log(LoggingLevel.ERROR, 'osf:ServiceAccount:prepReturn:Error', e);
        }
        return outputData;
    }
}