force-app/main/default/objects/osf_account_promotion__c/osf_account_promotion__c.object-meta.xml
<CustomObject>
    <label>Account Promotion</label>
    <nameField>
        <displayFormat>AP-{000}</displayFormat>
        <label>Account Promotions Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/osf_account_promotion__c/fields/osf_account__c.field-meta.xml
<CustomField>
    <fullName>osf_account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Promotions</relationshipLabel>
    <relationshipName>osf_account_promotions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/osf_account_promotion__c/fields/osf_promotion__c.field-meta.xml
<CustomField>
    <fullName>osf_promotion__c</fullName>
    <label>CC Promotion</label>
    <referenceTo>ccrz__E_Promo__c</referenceTo>
    <relationshipLabel>Account Promotions</relationshipLabel>
    <relationshipName>osf_account_promotions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/osf_servicePromotion.cls
/**
 * File:        osf_servicePromotion.cls
 * Project:     Abacus B2B (SP-ABCS-IFB-Abacus B2B Implementation (CCRZ))
 * Date:        Jan 8, 2020
 * Created By:  Ozgun Eser
  ************************************************************************
 * Description: Extension for Service Provider of CC Promotion Object
  ************************************************************************
 * History:
 */

global with sharing class osf_servicePromotion extends ccrz.ccServicePromotion {
    
    /**********************************************************************************************
    * @Name         : getFilterMap
    * @Description  : adds custom filters to CC Promotion Query's Where Clause.
    * @Created By   : Ozgun Eser
    * @param        : Map<String, Object>, inputData
    * @Return       : Map<String, Object>, outputData
    *********************************************************************************************/
    global override Map<String, Object> getFilterMap(Map<String, Object> inputData) {
        Map<String, Object> outputData = super.getFilterMap(inputData);
        try {
            Set<String> promotionIdSet = new Set<String> ();
            for(osf_account_promotion__c accountPromotion : [SELECT Id, osf_promotion__c FROM osf_account_promotion__c WHERE osf_account__c = :ccrz.cc_CallContext.currAccountId]) {
                promotionIdSet.add(accountPromotion.osf_promotion__c);
            }
            if(promotionIdSet.isEmpty()) {
                outputData.put(osf_constant_strings.DEFAULT_PROMOTIONS, osf_constant_strings.ACCOUNT_PROMOTION_DEFAULT_FILTER);
            } else {
                String queryFilter = osf_constant_strings.ACCOUNT_PROMOTION_FILTER_BEGIN;
                for(String promotionId : promotionIdSet) {
                    queryFilter += osf_constant_strings.ACCOUNT_PROMOTION_FILTER_ID + promotionId + osf_constant_strings.ACCOUNT_PROMOTION_FILTER_OR;
                }
                queryFilter = queryFilter.removeEnd(osf_constant_strings.QUERY_OR + osf_constant_strings.EMPTY_SPACE);
                queryFilter += osf_constant_strings.CLOSE_PARANTHESIS;
                outputData.put(osf_constant_strings.ACCOUNT_SPECIFIC_PROMOTIONS, queryFilter);
            }
        } catch (Exception e) {
            ccrz.ccLog.log(LoggingLevel.ERROR, 'osf:servicePromotion:getFilterMap:Error', e);
        }
        return outputData;
    }

}