force-app/main/default/objects/Contact/fields/osf_role__c.field-meta.xml
<CustomField>
    <fullName>osf_role__c</fullName>
    <description>Role of the User</description>
    <inlineHelpText>Role of the User</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard User</fullName>
                <default>true</default>
                <label>Standard User</label>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/osf_Abacus_B2B_config__c/osf_Abacus_B2B_config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Abacus B2B config</label>
</CustomObject>

force-app/main/default/objects/osf_Abacus_B2B_config__c/fields/License__c.field-meta.xml
<CustomField>
    <fullName>License__c</fullName>
    <description>license code</description>
    <label>License</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/osf_Abacus_B2B_config__c/fields/Server__c.field-meta.xml
<CustomField>
    <fullName>Server__c</fullName>
    <label>Server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/osf_Abacus_B2B_config__c/fields/Site_Key__c.field-meta.xml
<CustomField>
    <fullName>Site_Key__c</fullName>
    <label>Recaptcha Site Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/osf_ctrl_footer.cls
/**
 * File:        osf_ctrl_footer.cls
 * Project:     Abacus B2B (SP-ABCS-IFB-Abacus B2B Implementation (CCRZ))
 * Date:        Feb 10, 2020
 * Created By:  Cansu Aslı Aşcı
  ************************************************************************
 * Description: Controller class for footer page.
  ************************************************************************
 * History:
 * Date:                Modified By:            Description:
 * March,20             Oguz Alp                Removed the session cache partion since not essential
 *                                              Modified the getter methods.
 */
public with sharing class osf_ctrl_footer {
    
    private  osf_Abacus_B2B_config__c config;
    private Contact currContact;

    public osf_ctrl_footer(){
        if(config == null){
        	config = osf_Abacus_B2B_config__c.getOrgDefaults();    
        }
    }
    
    public String getServer(){
        return config.Server__c;
    }
    
    
    public String getLicense(){
        return config.License__c;
    }
    
    public Boolean getIsAdmin(){
        try {
            if(ccrz.cc_CallContext.isGuest) return false;
            if(currContact == NULL){
                currContact = [SELECT osf_role__c FROM Contact WHERE Id =: ccrz.cc_CallContext.currContact.Id];
            }
            return (currContact.osf_role__c == osf_constant_strings.ACCOUNT_ADMIN);            
        } catch (Exception ex) {
            return false;            
        }
    }
	
    public String getSitekey(){
        return config.Site_key__c;
    }

}