force-app/main/default/objects/Contact/fields/osf_allow_checkout__c.field-meta.xml
<CustomField>
    <fullName>osf_allow_checkout__c</fullName>
    <defaultValue>true</defaultValue>
    <description>if it is TRUE then the user is allowed to checkout, otherwise, he/she is not able to do that.</description>
    <inlineHelpText>if it is TRUE then the user is allowed to checkout, otherwise, he/she is not able to do that.</inlineHelpText>
    <label>Allow Checkout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/osf_role__c.field-meta.xml
<CustomField>
    <fullName>osf_role__c</fullName>
    <description>Role of the User</description>
    <inlineHelpText>Role of the User</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard User</fullName>
                <default>true</default>
                <label>Standard User</label>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Account Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/osf_supervisor_2__c.field-meta.xml
<CustomField>
    <fullName>osf_supervisor_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor 2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supervisor 2 Contacts</relationshipLabel>
    <relationshipName>osf_supervisor_2_contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/osf_supervisor__c.field-meta.xml
<CustomField>
    <fullName>osf_supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Supervisor Contacts</relationshipLabel>
    <relationshipName>osf_supervisor_contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/osf_ctrl_myaccount_myusers.cls
global without sharing class osf_ctrl_myaccount_myusers {
    /* 
    * @description  : getContacts 
    * @author       : Cansu Asli Asci
    * @createdDate  : Feb 28, 2020
    * @param        : ccrz.cc_RemoteActionContext context, 
    * @return       : ccrz.cc_RemoteActionResult result, containing return data
    */
    @RemoteAction
    global static ccrz.cc_RemoteActionResult getContacts(ccrz.cc_RemoteActionContext ctx, String isAdmin) {
        
        ccrz.cc_RemoteActionResult result = ccrz.cc_CallContext.init(ctx);
        Map<String, Object> data = new Map<String, Object> ();
        result.data = data;
        try{
            String contactId = osf_constant_strings.EMPTY_STRING;
            List<Contact> notAdminContacts = new List<Contact>();

            if(Boolean.valueOf(isAdmin)){
                notAdminContacts = [SELECT Id, AccountId, osf_role__c, Name, osf_allow_checkout__c, osf_supervisor__c, osf_supervisor_2__c FROM Contact WHERE AccountId = :ccrz.cc_CallContext.currAccountId];
            }
            data.put(osf_constant_strings.MYUSERS_CONTACTS, transformContacts(notAdminContacts));
            result.success = true;
        }catch(Exception ex){
        
            result.success = false;
           result.messages.add(osf_utility.createBeanMessage(ex));
        }
        return result;
    } 

    private static List<Map<String, Object>> transformContacts(List<Contact> contacts){
        List<Map<String, Object>> data = new List<Map<String, Object>> ();
        String supervisorName = osf_constant_strings.EMPTY_STRING;
        String supervisor2Name = osf_constant_strings.EMPTY_STRING;

        for(Contact cnt : contacts){
           
            if(String.isNotBlank(cnt.osf_supervisor__c)){
                supervisorName = [SELECT Name FROM Contact WHERE Id =: cnt.osf_supervisor__c].Name;
            }else{
                supervisorName = osf_constant_strings.EMPTY_STRING;
            }

            if(String.isNotBlank(cnt.osf_supervisor_2__c)){
                supervisor2Name = [SELECT Name FROM Contact WHERE Id =: cnt.osf_supervisor_2__c].Name;
            }else{
                supervisor2Name = osf_constant_strings.EMPTY_STRING;
            }

            data.add(
                new Map<String, Object>{
                    osf_constant_strings.MYUSERS_NAME => cnt.Name,
                    osf_constant_strings.MYUSERS_ROLE => cnt.osf_role__c,
                    osf_constant_strings.MYUSERS_ALLOW_CHECKOUT => cnt.osf_allow_checkout__c,
                    osf_constant_strings.MYUSERS_SUPERVISOR => supervisorName,
                    osf_constant_strings.MYUSERS_SUPERVISOR_2 =>supervisor2Name
                }
            );
        }

        return data;
    }
}